### ISSUE TITLE
Pixarbay API-Key

### ISSUE THREAD

**Issue by hinzke** [trilobit-gmbh/contao-pixabay-bundle#6]
Habe gerade versucht das Modul zu installieren nur gibt es unter Einstellungen keine Möglichkeit den API-Key einzugeben.

Eingesetzte Version 4.8.5 

Zitat Spooky 

> [..]Contao Palette Manipulator benutzt werden sollte, statt str_replace[..].

**Comment by trilobit-gmbh** [comment]
Bitte trage den Key in der config.yml ein:

```
contao:
  localconfig:
    pixabayApiKey: 'xxxxxxxx-xxxxxxxxxxxxxxxxxxxxxxxxx'
    pixabayImageSource: 'largeImageURL'
```
Die Einstellmöglichkeiten im Contao-Backend unter "Einstellungen" sollten obsolet werden/sein...
Ich werde dies aber bei Gelegenheit anpassen ;-) - (zu: Zitat Spooky)

Danke für den Hinweis.
